name: BlissPerms
main: Xenophilicy\BlissPerms\BlissPerms
version: 2.2.1
api: 3.0.0
loadbefore:
  - BehindBars
author: Xenophilicy
permissions:
  blissperms:
    default: op
    children:
      blissperms.colorchat:
        default: op
      blissperms.setprefix:
        default: op
        children:
          blissperms.setprefix.self:
            default: op
      blissperms.setsuffix:
        default: op
        children:
          blissperms.setsuffix.self:
            default: op
      blissperms.setperm:
        default: op
      blissperms.tier:
        default: op
        children:
          blissperms.tier.add:
            default: op
          blissperms.tier.remove:
            default: op
          blissperms.tier.list:
            default: op
          blissperms.tier.set:
            default: op
      blissperms.rank:
        default: op
        children:
          blissperms.rank.add:
            default: op
          blissperms.rank.remove:
            default: op
          blissperms.rank.list:
            default: op
          blissperms.rank.set:
            default: op
      blissperms.group:
        default: op
        children:
          blissperms.group.add:
            default: op
          blissperms.group.remove:
            default: op
          blissperms.group.list:
            default: op
          blissperms.group.set:
            default: op